const fs = require('fs');
const yaml = require('js-yaml');


const configurationFilePath = './configurations/elementql.yaml';
const configurationFile = fs.readFileSync(configurationFilePath);
const configuration = yaml.safeLoad(configurationFile, 'utf8');


const bootloaderContents =
`// ---
// File generated by ElementQL's metabootloader. Do not edit directly.
// ---

const {
    bootloader,
} = require('@plurid/elementql');

const configuration = ${JSON.stringify(configuration)};

bootloader(configuration);
`;


const bootloaderPath = './source/index.js';
fs.writeFileSync(bootloaderPath, bootloaderContents);
