// ---
// File generated by ElementQL's metabootloader. Do not edit directly.
// ---

const {
    bootloader,
} = require('@plurid/elementql');

const configuration = {
    "globals": {
        "react": "React",
        "react-dom": "ReactDOM"
    },
    "origins": {
        "elementql": "http://localhost:21100/elementql",
        "application": "http://localhost:8002"
    }
};

bootloader(configuration);
