// ---
// File generated by ElementQL's metabootloader. Do not edit directly.
// ---

const {
    bootloader
} = require('@plurid/elementql');

const configuration = {"globals":{"react":"React","react-dom":"ReactDOM"}};

bootloader(configuration);
